In [24]:
import tensorflow as tf

### Inisialisasi/deklarasi tensor

Inisialisasi konstan tensor / tensor constant

In [25]:
# Inisialisasi konstan dengan nilai 4
x= tf.constant(4)
print(x)

# Untuk mengambil nilai suatu tensor kita bisa memanggil method .numpy()
print('Nilai x',x.numpy())

# Kita juga bisa mendenfinisikan dtype dan shape nya
x= tf.constant(4, shape=(1,4), dtype=tf.float32)
print(x)

tf.Tensor(4, shape=(), dtype=int32)
Nilai x 4
tf.Tensor([[4. 4. 4. 4.]], shape=(1, 4), dtype=float32)


Tensor constant berbentuk matriks

In [26]:
# Tensor constant berbentuk matriks 2x3
matrix= tf.constant([[1,2,3],[4,5,6]])
print(matrix)

# Tensor constant tapi isi matriksnya satu semua
matrix_ones= tf.ones(shape=(2,2))
print(matrix_ones)

# Matriks identitas
matrix_identity= tf.eye(3)
print(matrix_identity)

# Matriks range, ini inklusif
matrix_range= tf.range(start=1, limit=5)
print(matrix_range)

# Matriks random:
# tf.random

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


### Casting dtype

Casting dilakukan dengan memanggil fungsi tf.cast(array, shape_baru)

In [27]:
float_matrix_range= tf.cast(matrix_range, tf.float32)
float_matrix_range

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

### Operasi Matematik

Misal terdapat 2 tensor untuk operasi matematik

In [43]:
x= tf.constant([[4,2],[1,2]])
y= tf.constant([[1,6],[3,5]])

In [47]:
# Penambahan
print('Penambahan', tf.add(x,y))
# Atau: x+y
print()

# Pengurangan
print('Pengurangan', tf.subtract(x, y))
# x-y
print()

# Perkalian
print('Perkalian', tf.multiply(x, y))
# x*y
print()

# Pembagian
print('Pembagian', tf.divide(x, y))
# x/y
print()

# Pemangkatan 2 (dari x) 
print('Pemangkatan', x**2)
print()

# Perkalian matriks
print('Perkalian matriks', tf.matmul(x, y))
# x@y
print()

Penambahan tf.Tensor(
[[5 8]
 [4 7]], shape=(2, 2), dtype=int32)

Pengurangan tf.Tensor(
[[ 3 -4]
 [-2 -3]], shape=(2, 2), dtype=int32)

Perkalian tf.Tensor(
[[ 4 12]
 [ 3 10]], shape=(2, 2), dtype=int32)

Pembagian tf.Tensor(
[[4.         0.33333333]
 [0.33333333 0.4       ]], shape=(2, 2), dtype=float64)

Pemangkatan tf.Tensor(
[[16  4]
 [ 1  4]], shape=(2, 2), dtype=int32)

Perkalian matriks tf.Tensor(
[[10 34]
 [ 7 16]], shape=(2, 2), dtype=int32)



In [55]:
a= [[1,2],
                        [3,4],
                        [5,6]]

### Indexing

Untuk indexing matriks 1d mirip2 dengan list biasa.

Misal terdapat matriks 2d seperti ini

In [52]:
matrix_2d= tf.constant([[1,2],
                        [3,4],
                        [5,6]])

matrix_2d

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

Untuk mendapatkan indeks ke [0][0]:

In [53]:
matrix_2d[0,0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

Indeks[1][:]

In [54]:
matrix_2d[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

### Reshape

tf.reshape(matriks, new_shape)

Misal matriks 1x9 mau direshape menjadi 3x3

In [59]:
matriks= tf.range(0,9)

matriks

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

Melakukan reshape

In [60]:
matriks_reshape= tf.reshape(matriks, (3,3))

matriks_reshape

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

Transpose matriks

In [61]:
matriks_transpose= tf.transpose(matriks_reshape)

matriks_transpose

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>